spring.config.import=optional:file:/vault/approles/auth-server.env,optional:vault://,optional:configserver:http://config-server:8888
spring.cloud.config.name=auth-server

# Config Server Retry Configuration
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=10000
spring.cloud.config.retry.multiplier=1.5
logging.level.org.springframework.cloud.config.client=INFO

# Vault Configuration
spring.cloud.vault.uri=https://vault:8200
spring.cloud.vault.authentication=APPROLE

spring.cloud.vault.ssl.trust-store=file:/vault/certs/vault.crt
spring.cloud.vault.ssl.trust-store-type=PEM

spring.cloud.vault.app-role.role-id=${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id=${VAULT_SECRET_ID}
