spring.config.import=optional:vault://,optional:configserver:http://config-server:8888
spring.cloud.config.name=auth-server

# Config Server Retry Configuration
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=10000
spring.cloud.config.retry.multiplier=1.5
logging.level.org.springframework.cloud.config.client= DEBUG

# Vault Configuration
spring.cloud.vault.host=vault
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=my-root-token
